route:
  group_by: ["instance", "severity"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: "slack-notifications"
receivers:
  - name: "slack-notifications"
    slack_configs:
      - send_resolved: true
        text: "{{ range .Alerts }}*[{{ .Labels.severity }}]* {{ .Annotations.summary }}\n{{ end }}"
        username: "Alertmanager"
        channel: "#alert"
        api_url: "https://hooks.slack.com/services/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"
