filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /usr/share/filebeat/logs/access.log
    fields:
      log_type: access_log
  - type: log
    enabled: true
    paths:
      - /usr/share/filebeat/logs/error.log
    fields:
      log_type: error_log
output.logstash:
  enabled: true
  hosts: ["logstash:5044"]

setup.kibana:
  host: "http://kibana:5601"
  username: "elastic"
  password: "changeme"

logging.level: warning